### ISSUE TITLE
Allow specification of ftp directory in config

### ISSUE THREAD

**Issue by mindok** [mindok/hugodeploy#3]
Currently files are copied to root directory of ftp server. It would be simple enough to add a rootdir option to the ftp config section and change to that directory when the ftp connection is initialised.

**Comment by adaptiman** [comment]
Yes, this would be a good feature because many hosts put the served site in public_html off of the FTP root.

**Comment by mindok** [comment]
Hi adaptiman. Done - readme updated with new setting.
